## MAKEFILE

CC = gcc -Wall -O3
LDFLAGS = -lm

all : exo1 exo2 exo3 exo4

exo1 : exo1.c
	$(CC) exo1.c -o exo1 $(LDFLAGS)
	
exo2 : exo2.c
	$(CC) exo2.c -o exo2 $(LDFLAGS)
	
exo3 : exo3.c
	$(CC) exo3.c -o exo3 $(LDFLAGS)

exo4 : exo4.c
	$(CC) exo4.c -o exo4 $(LDFLAGS)

	
clean: rm -f exo1 exo2 exo3 exo4
